defaults: &defaults
  working_directory: ~/openfisca-paris
  docker:
    - image: python:3.6.7

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip wheel
      - run:
          name: Install dependencies
          command: pip install . --upgrade && pip install ".[test]"
      - run:
          name: Run unit tests
          command: openfisca-run-test `circleci tests glob "tests/unittests/**/*.{yaml,yml}" | circleci tests split` --country-package openfisca_france --extensions openfisca_paris
      - run:
          name: Run specific tests
          command: openfisca-run-test `circleci tests glob "tests/*.{yaml,yml}" | circleci tests split` --country-package openfisca_france --extensions openfisca_paris

workflows:
  version: 2
  test:
    jobs:
      - test
